[package]
name = "ethereum_dev"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.14.0", features = ["full","node-bindings"] }

# async
tokio = { version = "1.44", features = ["full"] }

eyre = "0.6.12"

dotenv = "0.15.0"
